### PR TITLE
Add tryhard open source crate

### PR DESCRIPTION
**Pull request by davidpdrsn**
https://github.com/EmbarkStudios/tryhard was published yesterday.

### CODE REVIEW

**Review by lpil — APPROVED** [review]
Thank you

**Comment by lpil** [comment]
Build is failing for unrelated reasons. I'll fix this.

**Comment by repi** [comment]
Some weird linting errors on CI?

**Comment by lpil** [comment]
Yeah GitHub deprecated and removed some actions APIs. I just had to fix this for Gleam, shouldn't be a problem

**Comment by davidpdrsn** [comment]
Thanks 🙏

**Review by arirawr — APPROVED** [review]

**Pull request merged**
