### PR TITLE
Add:  Open source processes, policies, and info

### PR DESCRIPTION
**Pull request by soniasingla**
Signed-off-by: soniasingla <soniasingla.1812@gmail.com>

### Checklist

* [x] I have read the [Contributor Guide](../../CONTRIBUTING.md)
* [x] I have read and agree to the [Code of Conduct](../../CODE_OF_CONDUCT.md)
* [x] I have added a description of my changes and why I'd like them included in the section below

### Description of Changes

This PR adds [Open source processes, policies, and info](https://github.com/EmbarkStudios/opensource) at Embark!

### CODE REVIEW

**Comment by lpil** [comment]
The alignment looks a little off on mobile at the moment. Needs a little bit of CSS fidding!

image

I was wondering if having two call-to-action buttons on the hero image is too much?

**Comment by soniasingla** [comment]
@lpil another option could be adding text on the hero image after the line ` In our open source work, we're exploring and pushing the boundaries of new technologies, and sharing our learnings with the community.`, but I felt it will be over-texted!

**Comment by arirawr** [comment]
+1 to Louis' comment, needs a bit of tweaking!

**Comment by lpil** [comment]
Closing this due to inactivity. Thanks gang

**Pull request closed without merging**
