### PR TITLE
Change header and hero to match new aesthetic

### PR DESCRIPTION
**Pull request by celialewis3**
image

### Description of Changes

To mimic the color scheme and feel of the Embark Developer Discord server, this PR changes the header and hero sections of the website. Specifically:

- Adds "developer" after Embark logo, to differentiate between the traditional Embark website and the developer website, which is a common practice among other companies
- Changes color scheme for header to match Discord's
- Replaces the hero image with our Discord's current header image
- Minor wording changes

### CODE REVIEW

**Comment by celialewis3** [comment]
Fixed the alignment of the word "developer" as well as made the rest of the website match the color scheme. Should be good to go.

**Review by repi — COMMENTED** [review]
Very cool, looks good and fresh overall!

The sections with black text on pretty dark background may be a bit hard to read and looks a bit odd though. Is there something one could tweak around that here?

image

Maybe just trying a different background color for that?

**Comment by celialewis3** [comment]
I fixed it so dark mode (the mode captured in your screenshot) now mimics the color scheme of light mode, and I changed the font color to white and the background to a darker shade of orange for readability. Do you think this is more readable, or still requires tweaking?

image

**Review by repi — APPROVED** [review]
Nice, and yeah that looks better in the dark mode (forgot that our site supported that!)

**Pull request merged**
