### PR TITLE
Changed link color to blue

### PR DESCRIPTION
**Pull request by Deb77**

### CODE REVIEW

**Comment by arirawr** [comment]
Hey @Deb77 - the links here were purposefully white to make it easier to read on the black background (see below)


Could you explain the intention behind this PR? Is it difficult to tell that the links (which are currently white but underlined) are links as-is?

**Comment by Deb77** [comment]
yes i feel the links can be differentiated between from the rest of the
text unless pointed over using a mouse

**Comment by arirawr** [comment]
@Deb77 makes sense!

Since the default CSS blue is difficult to read on black and doesn't match the theme, maybe we can use Embark's blue colour instead? It's already a CSS variable, so you can use it like this: `color: var(--embark-blue);` 😄

**Comment by arirawr** [comment]
Closing this as I haven't heard from you in a week. Please open an issue if you would like to discuss the issue further!

**Pull request closed without merging**
