### PR TITLE
Add link to poll-promise

### PR DESCRIPTION
**Pull request by emilk**
### Checklist

* [x] I have read the [Contributor Guide](../../CONTRIBUTING.md)
* [x] I have read and agree to the [Code of Conduct](../../CODE_OF_CONDUCT.md)
* [x] I have added a description of my changes and why I'd like them included in the section below

### Description of Changes

Add the new repository https://github.com/EmbarkStudios/poll-promise

### CODE REVIEW

**Comment by celialewis3** [comment]
It seems this isn't passing a variety of our Netlify checks

**Comment by repi** [comment]
Ah think I fixed this on `main` and that it just needs a rebase

**Comment by repi** [comment]
@celialewis3 yup that solved it

**Review by celialewis3 — COMMENTED** [review]
Nice!

**Review by celialewis3 — APPROVED** [review]

**Pull request merged**
