### PR TITLE
added tag page

### PR DESCRIPTION
**Pull request by theosirian**
Implemented #1 

I wasn't sure about what to keep on the tag page, so I removed as little as possible.

Signed-off-by: Tiago Nascimento <xtheosirian@gmail.com>

### CODE REVIEW

**Comment by arirawr** [comment]
Hey @theosirian, thanks so much for the PR! 🎉 

Regarding the page design, I would cut out some of the other sections and add a clear way to get back to the home page. Something like this:
Screen Shot 2019-10-14 at 10 41 14

Also I notice that the tag page renders at /tags.html. Would it be possible to do this as a clean URL? You should be able to just use the bare URL in line 10 of script.js, and if that doesn't work then I need to change a setting on Netlify :)

Also, it looks like you ran a linter which changed a lot of the code unrelated to your changes. Could you provide me with the settings of the linter you ran? I realise there is no style guide in this repo which is my bad and I can set up a linter for it soon.

**Comment by arirawr** [comment]
Ah, one more thing - for the hover behaviour, let's keep it consistent with the rest of the site by doing a `transition: all .2s ease-in-out;` on `.tag` and a `transform: scale(1.05);` (or another scale factor that looks better) on `.tag:hover`. That way we also have less repetitive CSS.

**Comment by arirawr** [comment]
Hey @theosirian , any updates? I've left some feedback above.

**Comment by theosirian** [comment]
Hey, sorry about the delay, last week was busy.
I will make the requested changes.
About the linter I believe it was the default settings of eslint, but I will get back to you on this.

**Comment by arirawr** [comment]
@theosirian thanks! I added our own eslint config now, so you should be able to use that :)

**Comment by theosirian** [comment]
I have made the requested changes and rebased to the latest commit.

Also just realized I did it all in a single commit, when it should've been multiple, sorry.

**Comment by arirawr** [comment]
Thanks @theosirian ! No worries about the single commit, we'll sqaush it anyway :)

Looks like the symbol you're using for the back arrow doesn't work on all browsers (I'm using Mac Firefox). We already have fontawesome in the project so feel free to utilise that.
Screenshot 2019-10-29 at 12 34 56

Also, the hover effect isn't super clear - let's maybe make the scale factor a little bigger.
Screenshot 2019-10-29 at 12 35 23

It also looks like you've got a stylelint failure (sorry, I added that in recently!)

Thanks again for the contrib, this is looking really good!

**Comment by theosirian** [comment]
The scale factor wasn't actually working on the `a` element, so I wrapped it in a `div`.

I also changed the unicode character to a font-awesome icon and fixed the lint issue.

**Comment by arirawr** [comment]
LGTM - thanks for the PR! 🎉

**Pull request merged**
